version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=alive_dashboard
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge 